print("const.R")

# Feature Selction
SELECTED_VARS_ = "SELECTED_VARS_"
FEAUTRE_SELECTION_ALGORITHMS = c("LASSO_best", "LASSO_simple", "FORWARD")

SELECTED_VARS_LASSO = paste0(SELECTED_VARS_, "LASSO_")
SELECTED_VARS_LASSO_BEST = paste0(SELECTED_VARS_LASSO, "best")
SELECTED_VARS_LASSO_SIMPLE = paste0(SELECTED_VARS_LASSO, "simple")

SELECTED_VARS_FORWARD = paste0(SELECTED_VARS_, "FORWARD")



# Models
MODEL_ = "MODEL"

MODEL_LINEAR_REGRESSION = paste0(MODEL_, "REGRESSION")
MODEL_LINEAR_REGRESSION_VARS = paste0(MODEL_LINEAR_REGRESSION, "_VARS")

MODEL_TIMESERIES = paste0(MODEL_, "TIMESERIES")